from .fonts import FontsMixin
from .document import DocumentMixin
from .cover import CoverMixin
from .toc import TOCMixin
from .summary import SummaryMixin
from .errors import ErrorsMixin
from .recommendations import RecommendationsMixin
from .document import DocumentMixin
from .gauge import GaugeMixin
from .distribution import DistributionMixin
from .helpers import HelpersMixin
from .table_styles import TableStylesMixin
from .styles import StylesMixin
from .top_errors import TopErrorsMixin